---
# create_proxmox_vm.yml
- name: Agregar disco a Proxmox VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml


  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: Get VM configuration from Proxmox
      community.proxmox.proxmox_vm_info:        
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        name: "{{ vm_name | default(omit) }}"
        vmid: "{{ vm_id }}"
        config: current 
      register: vm_info  

    - name: Contar discos actuales
      set_fact:    
        disk_count: "{{ vm_info.proxmox_vms[0].config | dict2items | selectattr('key', 'match', '^scsi\\d+$') | list | length }}"
      when: vm_info.proxmox_vms | length > 0
    

    - name: Mostrar numero de discos
      debug:
        msg: "La VM {{ vm_id }} tiene {{ disk_count }} discos."


    - name: Show VM status
      ansible.builtin.debug:
        msg: "Current VM status is {{ vm_info_result.proxmox_vms[0].config }}"
      when: vm_info_result.proxmox_vms | length > 0


    - name: Create new disk in VM (do not rewrite in case it exists already)
      community.proxmox.proxmox_disk:
        <<: *proxmox_auth
        name: "vm-{{ vm_id }}-disk{{ disk_count }}"
        disk: "scsi{{ disk_count }}"
        backup: true
        cache: none
        storage: "{{ vm_storage }}"
        size: "{{ vm_disk_gb }}G"
        state: present
      when: disk_count is defined
      register: disk_task_result  



    - name: Mostrar resultado final
      debug:
        msg: disk_task_result

