---
# create_proxmox_vm.yml
- name: Crea una VM nueva en Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"
    vm_id: null

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: Create new VM with one network interface, three virto hard disk, 4 cores, and 2 vcpus
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "{{ vm_name | default('ansible-vm') }}"
        node: "{{ proxmox_node }}" 
        net:
          net0: "virtio,bridge={{ vm_bridge | default('vmbr0')}},tag={{ vm_vlan | default(omit) }}"
        cores: "{{ vm_cores | default(4) }}"
        #vcpus: 2  
        sockets: 1
        memory: "{{vm_memory_mb | default(2048) }}"      
        scsihw: "virtio-scsi-single"
        disks:
          - size: "{{ vm_disk_gb | default('20') }}G"
            type: "scsi"
            storage: "{{vm_storage | default('local-lvm') }}"
            storage_type: "lvm"
        state: present    
      register: create_vm_result