---
- name: crear Snapshot de una VM en Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"
    vm_id: null
    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: Set current time as a fact
      ansible.builtin.set_fact:
        my_timestamp: "{{ (now() - [community.general.to_timedelta('6 hours')] | first | default(timedelta(), True)).strftime('%Y-%m-%dT%H:%M:%S') }}"

    - name: crearcion de un snapshot de la VM
      community.proxmox.proxmox_snap:
        <<: *proxmox_auth
        node: "{{ proxmox_node }}" 
        vmid: "{{ vm_id }}"
        state: present
        snapname: "{{snap_name | default('snapshot-') }} + {{ my_timestam }}"
      when: vm_id is not none  
      register: new_snap_vm_result