---
# create_proxmox_vm.yml
- name: Listar VMs en Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  collections:
    - community.general
    - community.proxmox

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"
    vm_id: null

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: List all existing virtual machines on node
      community.proxmox.proxmox_vm_info:
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        type: qemu
      when: vm_id is none
      register: vm_list_info_result    

    - name: daata of existing virtual machines on node
      community.proxmox.proxmox_vm_info:
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        vmid: "{{ vm_id | default(omit) }}" 
      when: vm_id is not none 
      register: vm_info_result   

    - name: Extract OS disk description
      set_fact:
        os_disk_info: "{{ vm_info_result | json_query('proxmox[0].ide0') 
                          if vm_info_result.proxmox[0].ide0 is defined 
                          else vm_info | json_query('proxmox[0].scsi0') }}"  
      when: vm_info_result.proxmox | length > 0

    - name: Show OS disk info
      debug:
        msg: "OS Disk Info: {{ os_disk_info }}"
      when: os_disk_info is defined      

