---

- name: Storage Snapshot in VSPOne
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  vars:

    vsp_auth: &vspone_auth
      address: "{{ vspone_api_host }}"
      username: "{{ vspone_api_user }}"
      password: "{{ vspone_api_password | default(omit) }}"

  tasks:
    - name: Create a snapshot
      hitachivantara.vspone_block.vsp.hv_snapshot:
        state: present
        connection_info:
          <<: *vspone_auth  
        spec:
          primary_volume_id: {{ vsp_primary_volume_id }}  # ID del volumen primario a snapshotear 
          pool_id: {{ vsp_pool_id }}  # ID del pool donde se crea el snapshot
          snapshot_group_name: {{ vsp_snapshot_group_name | default("ansible_test_group") }}
      register: snapshot_result

   