---
# create_proxmox_vm.yml
- name: mover disco de Proxmox VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml


  vars:
    scsi_id: []

    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:

    - name: Move disk to another storage
      community.proxmox.proxmox_disk:
        <<: *proxmox_auth
        vmid: 105
        disk: "{{ item }}"
        target_storage: LUN04
        format: raw
        state: moved 

        async: 120
        poll: 10
      loop: "{{ scsi_id }}"
      register: moveResult 

    - name: Show snapshot Resut
      ansible.builtin.debug:
        var: moveResult