---
# create_proxmox_vm.yml
- name: Agregar disco a Proxmox VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml


  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmoxc_api_host }}"
      api_user: "{{ proxmoxc_api_user }}"
      api_token_id: "{{ proxmoxc_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmoxc_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:

    - name: Move disk to another storage
      community.proxmox.proxmox_disk:
        <<: *proxmox_auth
        vmid: 105
        disk: scsi7
        target_storage: local
        format: qcow2
        state: moved
      register: moveResult  