---
# create_proxmox_vm.yml
- name: playbook general de HDI
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  collections:
    - community.general
    - community.proxmox

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"
    vm_id: null
    vm_new_id: null

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: List all existing virtual machines on node
      community.proxmox.proxmox_vm_info:
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        vmid: "{{ vm_id }}"
        config: current 
      register: vm_info_result
      ignore_errors: yes

    - name: Display the raw configuration for inspection (optional)
      ansible.builtin.debug:
        var: vm_list_info_result.proxmox_vms
      when: vm_info_result.proxmox_vms | length > 0   

    - name: Fallar si la VM no existe
      fail:
        msg: "❌ La VM con ID {{ vm_id }} NO existe en Proxmox"
      when: vm_info_result is failed


    - name: Mostrar información básica de la VM
      debug:
        msg:
          - "✅ La VM {{ vm_id }} existe"
          - "Nombre: {{ vm_info_result.proxmox_vms[0].name | default('N/A') }}"
          - "Estado: {{ vm_info_result.proxmox_vms[0].status }}"
      when: vm_info_result.proxmox_vms | length > 0    

    - name: Start/Stop VM
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "{{ vm_name | default('ansible-vm') }}"        
        state: "stopped"
        timeout: 60 
      when: vm_info_result.proxmox_vms | length > 0   
      register: state_vm_result      

    - name: Remove VM 
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "{{ vm_name | default('vm-test')}}"
        node: "{{ proxmox_node | default('proxmox02') }}"
        state: absent        
      when: remove_vm  
      register: remove_result

    - name: Display Remove Result
      ansible.builtin.debug:
        var: remove_result    
      when: remove_vm   

    - name: Clonacion de VM
      ansible.builtin.include_tasks: cloneVMs.yaml
      timeout: 90 
      loop: "{{ range(1, n_vms + 1) | list }}" 
      when: clone_vm       
      register: cl_result

    - name: Agregar nueva interfaz  de red 
      community.proxmox.proxmox_nic:
        <<: *proxmox_auth
        vmid: "{{ vm_new_id }}"
        interface: "{{ interface_num  }}"
        mac: "{{ vm_nic_model | default(omit) }}"
        bridge: "{{ vm_bridge | default('vmbr0')}}"
        tag: "{{ vm_vlan | default( nic_tag , true) | int }}"
        link_down: "{{ is_down | default('false') | bool }}"
        model: "virtio"
        state: "present"
      when: vm_new_id is defined
      register: updateNIC_result

    - name: Start/Stop VM
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "{{ 'Clone-' vm_template_name '-' my_timestamp | default('ansible-vm') }}"        
        state: "{{ vm_state | default('started') }}"
        timeout: 60 
      when: vm_new_id is defined  
      register: state_vm_result      

