---
# create_proxmox_vm.yml
- name: envio de reporte
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  collections:
    - community.general
    - community.proxmox

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"
    vm_id: null
    vm_new_id: null

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:

    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: List finished tasks on node01
      community.proxmox.proxmox_tasks_info:
        <<: *proxmox_auth
        node: "{{ proxmox_node | default('proxmox01') }}"
        source: active
      register: result_tatsks



    # - name: Envia correo
    #   ansible.builtin.include_tasks: mailtask.yaml  
    #   register: ml_result
