---
# UpdateVM.yml
- name: Actualizar configuracion de una VM en Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  vars:
    add_nic: false
    interface_num: net0
    is_down: false
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"


    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: Obtener informacion de la VM
      community.proxmox.proxmox_vm_info:
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        name: "{{ vm_name | default(omit) }}"
        config: current 
      register: vm_info

    - name: Contar interfaces de red actuales
      set_fact:    
        net_count: "{{ vm_info.proxmox_vms[0].config | dict2items | selectattr('key', 'match', '^net\\d+$') | list | length }}"
        net_list: "{{ vm_info.proxmox_vms[0].config | dict2items | selectattr('key', 'match', '^net\\d+$') | list }}"
      when: vm_info.proxmox_vms | length > 0

    - name: Mostrar numero de NICs
      debug:
        msg: "La VM {{ vm_id }} tiene {{ net_count }} interfaces."

    - name: crear la nueva nic
      set_fact:    
        next_nic: "net{{ net_count }}"
      when: net_count is defined and add_nic

    - name: Mostrar NICs
      debug:
        msg: "{{ net_list }}"

    - name: obtener nic a actualizar
      set_fact:    
        nic_selected: "{{ net_list  | dict2items | selectattr('key', 'match', interface_num)}}"
      when: net_list | length > 0

    - name: obtener nic valores actuales
      set_fact:    
        nic_mac: "{{ nic_selected.split(',') | select('search', 'virtio=') | list | first | regex_replace('virtio=', '') }}"
        nic_tag: "{{ nic_selected.split(',') | select('search', 'tag=') | list | first | regex_replace('tag=', '') }}"
      when: net_list | length > 0   

    - name: Mostrar NIC seleccionada
      debug:
        msg: "La NIC {{ interface_num }} tiene {{ nic_mac }}, {{ nic_tag }} "
      when: net_list | length > 0  


    - name: Agregar nueva interfaz de red (net{{ net_count }})
      community.proxmox.proxmox_nic:
        <<: *proxmox_auth
        vmid: "{{ vm_id }}"
        interface: "{{ (add_nic == true) | ternary( next_nic , interface_num ) }}"
        mac: "{{ vm_nic_model | default(omit) }}"
        bridge: "{{ vm_bridge | default('vmbr0')}}"
        tag: "{{ vm_vlan | int if vm_vlan is defined else nic_tag }}"
        link_down: "{{ is_down | default('false') | bool }}"
        model: "virtio"
        state: "present"
      when: net_count is defined
      register: updateNIC_result

    - name: Get VM configuration from Proxmox
      community.proxmox.proxmox_vm_info:        
        <<: *proxmox_auth
        node: "{{ proxmox_node }}"  
        name: "{{ vm_name | default(omit) }}"
        type: qemu
        config: current 
      when: vm_name is not none 
      register: vm_info_result   
      delegate_to: localhost

    - name: Show clone result
      ansible.builtin.debug:
        var: vm_info_result         
