---
# create_proxmox_vm.yml
- name: Crear VM en Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yaml

  vars:
    api_host_url: "https://{{ proxmox_api_host }}:8006/api2/json"

    proxmox_auth: &proxmox_auth
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
      validate_certs: false

  tasks:
    - name: Validar credenciales (token o password)
      assert:
        that:
          - (proxmox_api_token_id is defined and proxmox_api_token_secret is defined) or (proxmox_api_password is defined)
        fail_msg: "Debes definir token (ID y Secret) o password para la API de Proxmox."

    - name: Set current time as a fact
      ansible.builtin.set_fact:
        my_timestamp: "{{ now().strftime('%Y-%m-%dT%H%M%SZ') }}"

    - name: Crear VM desde plantilla (si aplica)
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "Clone-{{ vm_template_name }}-{{ my_timestamp }}"
        clone: "{{ vm_template_name }}"
        node: "{{ proxmox_node | default('proxmox03') }}"
        storage: "{{ vm_storage }}"
        full: "{{ vm_full }}"
        format: "{{ vm_format }}"
        timeout: 2000
        state: present
      register: clone_result

    - name: Show VM by Template Resut
      ansible.builtin.debug:
        var: clone_result      

    - name: Encender la VM
      community.proxmox.proxmox_kvm:
        <<: *proxmox_auth
        name: "{{ vm_name | default('ansible-vm') }}"    
        state: started
      register: StartVM-result  

    - name: Show VM Start Resut
      ansible.builtin.debug:
        var: StartVM-result        
